modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/SilentChaos512/Treasure-Bags/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/treasure-bags"
logoFile="logo.png"
#credits=""
authors="SilentChaos512"

[[mods]]
    modId="treasurebags"
    version="${file.jarVersion}"
    displayName="Treasure Bags"
    #updateJSONURL="http://myurl.me/"
    description='''
    Configurable loot bags with infinite possibilities! Control loot with loot tables and bag appearance with JSON files.
    '''

[[dependencies.treasurebags]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.treasurebags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.treasurebags]]
    modId="silentlib"
    mandatory=true
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"
